QueueDocumentWorker:
  every:
    - "2s"
  # '00 14 * * *' 14h perday
  # '5 23 * * * America/Chicago' 25:05
  # you can use rufus-scheduler "every" syntax in place of cron if you prefer
  # every: 1h
  # By default the job name (hash key) will be taken as worker class name.
  # If you want to have a different job name and class name, provide the 'class' option
  queue: default
  args:
  description: "This job queues all content for indexing in solr"
